### PR TITLE
Updated for Lottie 4.0.1

### PR DESCRIPTION
**Pull request by Mcrich23**
Made necessary name changes to be compatible with Lottie 4.0.1

### CODE REVIEW

**Comment by tfmart** [comment]
Hi @Mcrich23, thanks for your contribution! I see you've mentioned that you had to make some name changes to update the Lottie version. Did you had to rename any of the components or the library itself?

**Comment by Mcrich23** [comment]
@tfmart No I didn't, the issue is Lottie renamed some things and deprecated some stuff, so all I did was I changed it to the new names.

**Comment by Mcrich23** [comment]
I have also tested it and it works!

**Comment by tfmart** [comment]
@Mcrich23 awesome, everything looks good on my end as well. Thanks for your contribution!

**Comment by tfmart** [comment]
I've also created a new version with the changes on this PR
https://github.com/tfmart/LottieUI/releases/tag/v.1.3.2

**Comment by Mcrich23** [comment]
Of course.

**Pull request merged**
